### ISSUE TITLE
Sort Order Problem

### ISSUE THREAD

**Issue by selsie** [loot/skyrimse#1134]
[More Enchant Ranks for Ordinator](https://www.nexusmods.com/skyrimspecialedition/mods/9275)
[Ordinator - Perks of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/1137)

The mod **Ordinator - Perks of Skyrim.esp** has to be loaded before **Ordinator - More Enchantig Ranks.esp**
Unfortunately the 1st mod is not explicitely entered as master in the 2nd, so the 2nd mod doesn't work for many people who use LOOT

**Comment by MacSplody** [comment]
Transferred to relevant repository, I've also added links to mods.

**Comment by MacSplody** [comment]
> The mod **Ordinator - Perks of Skyrim.esp** has to be loaded before **Ordinator - More Enchantig Ranks.esp**
> Unfortunately the 1st mod is not explicitely entered as master in the 2nd, so the 2nd mod doesn't work for many people who use LOOT

@selsie It won't sort after it because `Ordinator - Perks of Skyrim.esp` is not a master file for `Ordinator - More Enchanting Ranks.esp`. 
LOOT won't sort them as expected if it doesn't know two plugins are related. 
It can be explicitly told via Master files or LOOT rules.

![image](https://user-images.githubusercontent.com/1944639/81022844-97a1e780-8e66-11ea-9046-c2b706e0a9e0.png)

- [x] Add requirement to `Ordinator - More Enchanting Ranks.esp`.

**Comment by MacSplody** [comment]
@selsie Update your masterlist, it will sort correctly now. Thanks for reporting the issue.
