### ISSUE TITLE
Diversity is too high in load order

### ISSUE THREAD

**Issue by luotinen** [loot/skyrimse#1291]
"﻿STEP 2: Check your load order.  ﻿If using LOOT, it will NOT yet recognize my mod. 
﻿Go to your plugins.  Find "Diversity - A Character Overhaul.esp" and drag it to the bottom."
Source: https://www.nexusmods.com/skyrimspecialedition/mods/5291?tab=description

**Comment by MacSplody** [comment]
> Check your load order. ﻿If using LOOT, it will NOT yet recognize my mod.
> ﻿Go to your plugins. Find "Diversity - A Character Overhaul.esp" and drag it to the bottom."

That isn't going to work for every load order, and in most cases, NPC appearance mods are going to need patches.
You could put it last, but it's just a brute force approach and can break other mods.
Smaller mods with only a single or several NPCs would have to be given priority.
Who's going to check for all these smaller plugins?

There's also the problem of loose vs packed assets, which can lead to the grey/black face bug.
You can give plugins with loose files priority, but it may overwrite a smaller mod with an archive e.g. `.bsa`.

Personally, I don't think there's an optimal order for NPC appearance mods. Because a lot of times it comes down to user preference of how a mod changes that NPCs appearance, not the actual contents of the plugins.

If you want to place `Diversity - A Character Overhaul.esp` after a specific mod you can use a load after rule.
If you want to give it priority over most other mods you can add it to a group after the default group.

If you have specific mods you think should be before `Diversity - A Character Overhaul.esp` that you think LOOT is sorting incorrectly, then I'd be happy to have a look at them and test them out.

**Comment by MacSplody** [comment]
> If you have specific mods you think should be before Diversity - A Character Overhaul.esp that you think LOOT is sorting incorrectly, then I'd be happy to have a look at them and test them out.

Closing due to lack of feedback.
