### ISSUE TITLE
Is a single branch for a large number of load order contributions sufficient?

### ISSUE THREAD

**Issue by oblivioncth** [loot/skyrimse#1411]
I would like to contribute a large number (several dozen) of simple "Load After" changes to the masterlist that are currently missing.

All of them are based on express load order instructions from each mods description or are straightforward entries that ensure compatibility patches load after the two mods they are for.

I will make each entry or group of related entries a separate commit for easy review and a clean history, but having a topic branch for each would be quite cumbersome.

I figure this is satisfactory but just wanted to ask since I haven't contributed to this project before.

**Comment by Ortham** [comment]
I think a single branch is fine, they're all thematically-related commits.

**Comment by MacSplody** [comment]
> a large number (several dozen) of simple "Load After" changes to the masterlist that are currently missing.

Some rules listed on mod pages are missing due to problems they can cause for certain load orders.
Other rules aren't listed or included, and are express instruction given by the mod authors in their mod page comment section.

Here is an overall view of a small load order.
Even in this small sample we can't follow all instructions.
We'd have to ignore some, to allow freedom of choice.

As long as it's not about placing Immersive Citizens or Relationship Dialogue Overhaul after anything else then it should be fine.

![image](https://user-images.githubusercontent.com/1944639/96388665-39fa2100-11a2-11eb-88ec-80fec25d5dbf.png)

![image](https://user-images.githubusercontent.com/1944639/96390076-c0b2fc00-11aa-11eb-9115-044eb6a6a779.png)

![image](https://user-images.githubusercontent.com/1944639/96390479-d1647180-11ac-11eb-9833-78699784c41d.png)

**Comment by oblivioncth** [comment]
@MacSplody That is a very fair point. With every mod you add to a particular load order it becomes more and more likely that a order conflict will occur that would create a circular dependency and it would obviously be up to the user to decide how they want to handle that.

I'll be very selective in my contributions.

**Comment by MacSplody** [comment]
> @MacSplody That is a very fair point. With every mod you add to a particular load order it becomes more and more likely that a order conflict will occur that would create a circular dependency and it would obviously be up to the user to decide how they want to handle that.
> 
> I'll be very selective in my contributions.

if there's a good enough reason to add a rule, then feel free to suggest it.
It can always be reviewed if it ever causes an issue for a user.
