### ISSUE TITLE
Castle Volkihar Rebuilt tags

### ISSUE THREAD

**Issue by Arthmoor** [loot/skyrimse#1542]
The C.Owner tag is added to CVR by LOOT and should not be. CVR does not make any ownership changes to any of the cells it edits.

**Comment by sibir-ine** [comment]
I added it a while ago because CVR adds the Public Area flag to Volkihar North Tower (02007203).

**Comment by Arthmoor** [comment]
It does, yes, and I'm hard pressed to remember exactly why. In any case, that wouldn't be a C.Owner thing. That would be a record flags issue.

**Comment by sibir-ine** [comment]
According to WB's documentation, C.Owner covers that flag. I did a quick test to confirm, & it does indeed. ~~I believe C.RecordFlags is for flags not covered by other tags such as C.Owner.~~ C.RecordFlags is for record flags, not data flags.

**Comment by Arthmoor** [comment]
I guess this is what I get for not keeping up on the docs and other changes that have been happening. :P

I guess this can be closed then, and if I remember why I added the public space flag to begin with I'll worry about it then.

**Comment by MacSplody** [comment]
> 
> 
> According to WB's documentation, C.Owner covers that flag. I did a quick test to confirm, & it does indeed. I believe C.RecordFlags is for flags not covered by other tags such as C.Owner.

There's a new tag `C.MiscFlags` in the latest WB nightly, it was added by infernio in https://github.com/wrye-bash/wrye-bash/commit/e3557036cbccba36c6e98b9cb6363e2ae05a926e

> I guess this is what I get for not keeping up on the docs and other changes that have been happening. :P
>
> I guess this can be closed then, and if I remember why I added the public space flag to begin with I'll worry about it then.

It didn't work correctly before though, it was fixed in https://github.com/wrye-bash/wrye-bash/commit/eaeb8319f223fc9b8c37ac445676f89439215a06.

---

Since we are on the subject of tags, there were some tag changes made for cutting room floor a while back.
https://github.com/loot/skyrimse/pull/1359

And some users have brought it up thinking it would cause issues.

The reason we suggested removing tag was because it was a change forwarded from USSEP.
With USSEP receiving the `Actors.DeathItem` tag instead, the change will still be forwarded.

**Comment by MacSplody** [comment]
> I guess this is what I get for not keeping up on the docs and other changes that have been happening. :P
> 
> I guess this can be closed then, and if I remember why I added the public space flag to begin with I'll worry about it then.

Closing as it's resolved.
