### ISSUE TITLE
LootDebug Error (Skyrim Radioactive | Old masterlist v0.10)

### ISSUE THREAD

**Issue by Reggit6182** [loot/skyrimse#1602]
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/6014277/LOOTDebugLog.txt)
I am not sure what the exact issue here is could some one assist me please?

**Comment by Ortham** [comment]
```
[16:38:39.461822] [error]: Exception while executing query: exists: The filename, directory name, or volume label syntax is incorrect.
: "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Skyrim Radioactive -.*\.esp"
```

Somehow you're using a very old version or branch of the masterlist, check that the masterlist branch in LOOT's settings is `v0.15`.

**Comment by Reggit6182** [comment]
![image](https://user-images.githubusercontent.com/57755519/108593339-c4f05f80-73be-11eb-903b-4bbd4fb1b7fc.png)
It says it's v0.15

**Comment by Ortham** [comment]
What happens if you try updating your masterlist?

**Comment by Reggit6182** [comment]
I click on the button but nothing happens. Do I have to manually do this? I am running LOOT as admin as well.

**Comment by Ortham** [comment]
No, LOOT should update the masterlist whenever you sort too (because you've got the "Update masterlist before sorting" toggle enabled). 

It shouldn't make a difference if you run as admin or not, all of the files LOOT writes are in your user's local app data folder. Can you share your debug log after trying to update the masterlist?

**Comment by Reggit6182** [comment]
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/6014799/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Ah, it's failing because LOOT is failing to initialise properly because of the old masterlist.

If you go to `%LOCALAPPDATA%\LOOT\Skyrim Special Edition\` and delete the `.git` folder (it might be hidden) and the `masterlist.yaml` file there, LOOT should start up properly and you should then be able to download the latest masterlist.

**Comment by Reggit6182** [comment]
Ahh, that was the trick you are a legend thank-you for your help. Is there a way I can give +rep? Or a show of appreciation?

**Comment by Ortham** [comment]
If you want, you can send me money [here](https://paypal.me/OliverHamlet), but there's no rep system or anything like that, and a thank you is enough. 😃
