### ISSUE TITLE
JK's Skyrim: The Great Cities incompatibility & patch message don't look for The Great Cities of JK's North - Patch.esp

### ISSUE THREAD

**Issue by puddles54** [loot/skyrimse#1611]
I'm not really familiar with GitHub and pull requests and can't really figure it out quickly otherwise I'd submit one myself but it recommends The Great Cities of JK's North patch but doesn't find the correct .esp name. It might have been changed in an update perhaps.

On line 14497 of the current masterlist it has:

```yaml
condition: 'checksum("JKs Skyrim.esp", 8E2CDE40) or (not active("The Great JK''s Cities.esp") and not active("The Great Cities of JK''s Skyrim - Patch.esp"))'
```

I think it should be:

```yaml
condition: 'checksum("JKs Skyrim.esp", 8E2CDE40) or (not active("The Great JK''s Cities.esp") and not active("The Great Cities of JK''s North - Patch.esp"))'
```

This just changes "Skyrim" to "North" in the .esp name. Or if it should support both the new(?) name and the old(?) name of the esp I think this will do it:

```yaml
condition: 'checksum("JKs Skyrim.esp", 8E2CDE40) or (not active("The Great JK''s Cities.esp") and not active("The Great Cities of JK''s Skyrim - Patch.esp") and not active("The Great Cities of JK''s North - Patch.esp"))'
```

**Comment by sibir-ine** [comment]
It looks like `The Great Cities of JK's Skyrim - Patch.esp` is the patch for TGC & JKS while `The Great Cities of JK's North - Patch.esp` is the patch for TGC, CotN, & JKS, so both should hide the message.

Also, it looks like `The Great JK's Cities.esp` is outdated, & the author recommends The Great Cities of JK's North; that should be addressed too.

It also looks like the author of The Great Cities of JK's North changed the recommended load order since it was added to the masterlist, so that should be addressed too.

- [x] Check for North version of patch
- [x] Remove check for outdated patch
- [x] Add `useInstead` message to outdated patch
- [x] Revise other mentions of non-CotN version of patch
- [x] Revise load order rules for involved mods
- [x] Add `useInstead` message for non-CotN Winterhold version of CotN patch
- [x] Misc. cleaning updates

**Comment by sibir-ine** [comment]
@fenrir0054 Done in d7c2f5d. I updated the general handling of the patch since it seems to have been updated significantly since the last time it was updated in the masterlist.
