### ISSUE TITLE
Add listing for "World of Rudra"

### ISSUE THREAD

**Issue by cecell** [loot/skyrimse#1766]
This is an off-site abandoned mod but one that still has a following.  The link isn't really official but i'll include it outside of the block.  You can make the choice to include it or not:

    url: [ 'https://general-andreis.tumblr.com/post/162162012046/mod-shoutout-world-of-rudra-by-bee9999-im-still' ]

  - name: 'Worldofrudra.esm'
    dirty:
      - <<: *quickClean
        crc: 0xE73DA8F2
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 14
    clean:
      - crc: 0x67B3DBD0
        util: 'SSEEdit v4.0.3'

**Comment by sibir-ine** [comment]
@cecell Is that link from the original author? If not, has the author given them permission or otherwise allowed the mod to be distributed freely on other sites? If not, it may not be the best idea to add it unless you can provide an official location.

**Comment by pStyl3** [comment]
That website holds a download link that links to `mega.nz` - which itself is very uncommon as a `url` within LOOT's masterlist, but not out of the question. Our masterlist for Fallout 3 does contain such a link for example, so we could use that theoretically.

That being said, and basically what @sibir-ine is saying, I don't think that this `tumblr` page is what we are looking for, as I also don't see a proof that the creator of the tumblr page has permission to reupload the mod to `mega`. In fact, he even writes ` so I’ve decided to mirror the latest version to make it easier to obtain, otherwise, you’ll have to sign up for a few sites.`.

It might be possible to link to the original Chinese website, but I don't know which page would be the correct one.

**Comment by cecell** [comment]
Idk that's why I left it up to y'all.  I'd say don't bother putting it in
there personally. Then you're done!  I haven't read anything anywhere
claiming/stating that any permissions were given by anyone at anytime,
sorry.  I'm sadly monolingual as well and have a sneaking suspicion that
any such statements wouldn't be in english.  The ESM file is 93MB though
and the world is supposedly like double the size of Skyrim so I'm looking
forward to playing around with it :D

**Comment by sibir-ine** [comment]
@cecell Then we'll close this for now.
