### ISSUE TITLE
Project New Reign - Nemesis PCEA

### ISSUE THREAD

**Issue by KhrysINXS** [loot/skyrimse#1807]
[Project New Reign - Nemesis PCEA](https://www.nexusmods.com/skyrimspecialedition/mods/31667)

Implement a message of sorts instructing the user how to resolve that error/corrupt or broken module. Being aware now that each Nemesis Batch run edits the plugin in a way that adds null bytes to it; just so the user doesn't get confused by the LOOT message saying that its broke; perhaps a bit of an explanation what's happened and a method of replacing the plugin with a fresh one will act as a workaround to not solve the matter but deal with it temporarily.

**Comment by sibir-ine** [comment]
Keep in mind that due to the way the plugin ends up getting corrupted, LOOT will not only show a message saying it's invalid but also hide its plugin card, so the message won't be displayed then. The message would have to be persistent & be something like "If LOOT discovers this plugin to be invalid, do XYZ to fix it." That way, even though people won't see it when they really need it, hopefully they'll keep it in mind in case they come across the issue.

I'd also like to do some research/testing & get more confirmation before adding such a message.

**Comment by MacSplody** [comment]
The only thing we could reliably do, is to always show a global message if that file is present.
Is there a concise way to explain the problem?

Are there steps to reproduce the issue btw?

**Comment by MacSplody** [comment]
Tested and managed to generate a corrupted plugin.
No steps to replicate yet.
![image](https://user-images.githubusercontent.com/1944639/120914176-27cae580-c694-11eb-9426-1f1a2853d2e8.png)
