### ISSUE TITLE
Apocalypse - Magic of Skyrim - Wild Edit warning references non-existant cell record

### ISSUE THREAD

**Issue by SierraKomodo** [loot/skyrimse#2005]
- LOOT Version: 0.16.1
- LOOT Masterlist Revision: bbcda59
- Apocalypse Version: 9.45.0 - Current main file shown on the Nexus page https://www.nexusmods.com/skyrimspecialedition/mods/1090?tab=files

When running LOOT for a load order that contains `Apocalypse - Magic of Skyrim.esp`, the following message is presented by LOOT for the plugin:

> This plugin contains wild edits and may require additional manual cleaning to not interfere with other mods. Remove CELL 00009B79 from Apocalypse - Magic of Skyrim.esp

I may be misunderstanding what the message is saying to do, but when loading the plugin in xedit, this cell doesn't exist under the Apocalypse ESP. Here are the cells that do come up:

![SSEEdit_2021-08-31_19-19-57](https://user-images.githubusercontent.com/11140088/131601369-e47e9a59-5731-4105-86be-00ee8792e1f3.png)

When searching `00009B79`, the only hits are a cell record under `Skyrim.esm`. Here's what xedit shows me for this record while the Apocalypse plugin is loaded - It doesn't appear there are any actual edits to the record here, but I'm far from a xedit expert.

![SSEEdit_2021-08-31_19-20-24](https://user-images.githubusercontent.com/11140088/131601479-91e78f05-bc95-4168-a99a-1a72ee68ab4d.png)

**Comment by MacSplody** [comment]
> I may be misunderstanding what the message is saying to do, but when loading the plugin in xedit, this cell doesn't exist under the Apocalypse ESP. Here are the cells that do come up:

The Wild Edit is in the Worldspace Cells or Exterior Cells.

![image](https://user-images.githubusercontent.com/1944639/131604576-9fb1f1bb-f3a6-4d55-96d7-73a4eca1aafa.png)

Anything under **Cell** is for interior cells.

![image](https://user-images.githubusercontent.com/1944639/131604663-7ec7b3ca-5d38-404e-b02e-d44a34b0dd43.png)


The reason it's marked as a wild edit, is because it changing something it shouldn't be.
In this case the water record type is being removed.

![image](https://user-images.githubusercontent.com/1944639/131604118-c915bf5b-167a-4499-ab66-e0d1929cba44.png)

That change was made in `Update.esm`
![image](https://user-images.githubusercontent.com/1944639/131604924-dd29b552-26be-4070-ac3a-1ad320096bc6.png)

Some water mods may correct it anyway.

![image](https://user-images.githubusercontent.com/1944639/131604760-991fd61d-39ae-4713-8af0-4f34224fafd6.png)

**Comment by SierraKomodo** [comment]
Gooot it. Not a LOOT or masterlist issue then, a ID10T error on my part lol.
