### ISSUE TITLE
Paper Maps Framework needs to be at the bottom no matter what or else it won't work.

### ISSUE THREAD

**Issue by woodyafortunato** [loot/skyrimse#2013]
https://www.nexusmods.com/skyrimspecialedition/mods/29932?tab=posts
Why doesn't loot just know to put this at the bottom already? I had tried to make a custom rule to load it below Synthesis patch but it keeps saying its cyclical error:

Error
Failed to sort plugins. Details:
Cyclic interaction detected between "Atlas Map Markers.esp" and "FWMF for Paper Map by Mirhayasu.esp":

Atlas Map Markers.esp
 [Group]
Bashed Patch, 0.esp
 [Group]
DynDOLOD.esp
 [Master]
Synthesis.esp
 [User Load After]
FWMF for Paper Map by Mirhayasu.esp
 [Group]
Atlas Map Markers.esp

**Comment by MacSplody** [comment]
> Why doesn't loot just know to put this at the bottom already?

Because no asked for or submitted changes for that mod,
I wouldn't put it at the end anyway, it should be fine in the Worldspace Settings group as nothing will overwrite it then.
It would also need a few load after rules for anything else in Worldspace Settings group like Atlas Map Markers.
And patches for anything it overwrites in your load order.

> I had tried to make a custom rule to load it below Synthesis patch but it keeps saying its cyclical error:

You're trying to load a file "Synthesis.esp" or "DynDOLOD.esp" before one of its Master Files.
It's not possible to do that, and those files would need to be remade if you want to place `FWMF for Paper Map by Mirhayasu.esp` last.

**Comment by woodyafortunato** [comment]
Very helpful Mark it as solved and move on ffs

**Comment by MacSplody** [comment]
> Very helpful Mark it as solved and move on ffs

From the information you've provided, the problem appears to be on your end.
There are no updates I can make that will fix your sorting error.

If you think that's not the case then you'll need to provide more information.
[How To Report Issues Helpfully](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)
