### ISSUE TITLE
Wearable Lanterns & Wearable Lanterns MCM Fix

### ISSUE THREAD

**Issue by UUFrost1** [loot/skyrimse#2293]
This isn't a bug, so much as an evolution.

After downloading Chesko's [Wearable Lanterns mod](https://www.nexusmods.com/skyrimspecialedition/mods/7560), LOOT recommends that you also use [Wearable Lanterns MCM Fix](https://www.nexusmods.com/skyrimspecialedition/mods/25372). This fix is out of date and reports indicate that it no longer works. The fix that works is [Chesko's Wearable Lanterns - SE and VR Patch](https://www.nexusmods.com/skyrimspecialedition/mods/19348).

**Comment by sibir-ine** [comment]
Thanks for the report! Just a few notes for updating the mod's entry in the masterlist:
* `patchUpdateAvailable` would be more appropriate than `alsoUseX`.
* The loose, patched `scripts/_wl_compatibility.pex` file will have to be used to tell if SE & VR Patch is installed or not, preferably by checksum (unpatched: `7DA73A58`, patched: `02E2CA8E`) in case users unpack the WL BSAs.
* SE & VR Patch is only relevant for users with SKSE installed, so that should also determine whether the message is displayed.
* SE & VR Patch seems to remove the toggle & settings powers in favor of the MCM, so a conditional `requiresMCM` message should be displayed.
* PapyrusUtil SE is required for full functionality of the MCM (i.e., saving & loading profiles), so a conditional `PapyrusUtil` requirement should be added.
* It may actually be beneficial to continue to recommend MCM Fix as it includes a few resources that SE & VR Patch doesn't (i.e., the meter widget & the menu image). However, we should recommend deleting the bundled `StorageUtil.dll` plugin as this is the LE version of PapyrusUtil.

**Comment by sibir-ine** [comment]
@UUFrost1 Thanks for the report! I've updated the masterlist to reflect my findings above. Please let us know if you have further questions or concerns.
