### ISSUE TITLE
xEdit Error: "Cutting Room Floor.esp" has a lower load order than "Relationship Dialogue Overhaul.esp"

### ISSUE THREAD

**Issue by ghyujkilop** [loot/skyrimse#2365]
I only get two errors from xEdit. This is one of them, the other is: ModGroup "Guard Dialogue Overhaul" is invalid:

Full log looks like:

[01:03] ModGroup "Guard Dialogue Overhaul" is invalid:
[01:03]  - Error: "Cutting Room Floor.esp" has a lower load order than "Relationship Dialogue Overhaul.esp"

Can you add something so that this is resolved?

**Comment by sibir-ine** [comment]
The error is just saying that the mod group can't be used because your current load order doesn't match its load order. A mod group just hides conflicts in xEdit, so it's not something to worry about unless you actually want to use it (nor is it an issue with LOOT, for that matter).

As to whether we should enforce that order, IIRC, _Cutting Room Floor_ does get sorted after _Relationship Dialogue Overhaul_ by default unless you have _Immersive Citizens_ installed. _ICAIO_ is in the **Core Mods** group (which loads after the default group) & _RDO_ is set to load after it on the advice of both authors (_RDO_ incorporates _ICAIO_ changes in overlapping records), so _ICAIO_ will essentially hoist _RDO_ later in your load order & therefore later than _CRF_ (which is in the default group). I think this has come up several times &, IIRC, we haven't sorted everything out yet as it may require an overhaul to our groups for SSE. If you want _CRF_ to load after _RDO_ on your end, you can [add your own](https://loot.readthedocs.io/en/stable/app/usage/plugin_editor.html) load after rule. You can also move _ICAIO_ to an earlier group if they all end up sorting too late for your purposes.

**Comment by sibir-ine** [comment]
I'll move the issue of load order & groups for the mods concerned to #2200 so it can be part of the larger project of overhauling our groups for SSE. The xEdit mod group issue doesn't pertain to LOOT, nor is it a concern in general, so I'll close this issue.
