### ISSUE TITLE
Mods Editing Vanilla Homes and ELFX "No Homes" Modules Load Order Matter 

### ISSUE THREAD

**Issue by KhrysINXS** [loot/skyrimse#2367]
Eli_Breezehome.esp https://www.nexusmods.com/skyrimspecialedition/mods/48931 
needs to load after:
ELFX - NoBreezehome.esp
ELFX - NoPlayerHomes.esp
possibly the others too that are not meant to touch anything in the WhiterunBreezehome Cell (didn't check) from:
Enhanced Lights and FX https://www.nexusmods.com/skyrimspecialedition/mods/2424

WHATS HAPPENING
Even though they are defined as "NO Home" not adding new effects and what not; the modules still edit and rearrange object REFR's all throughout the Cell (mainly vanilla REFR's) breaking intentional edits per vanilla REFR from the custom home mod overhauls

**Comment by MacSplody** [comment]
> Eli_Breezehome.esp https://www.nexusmods.com/skyrimspecialedition/mods/48931 needs to load after: ELFX - NoBreezehome.esp ELFX - NoPlayerHomes.esp possibly the others too that are not meant to touch anything in the WhiterunBreezehome Cell (didn't check) from: Enhanced Lights and FX https://www.nexusmods.com/skyrimspecialedition/mods/2424
> 
> WHATS HAPPENING Even though they are defined as "NO Home" not adding new effects and what not; the modules still edit and rearrange object REFR's all throughout the Cell (mainly vanilla REFR's) breaking intentional edits per vanilla REFR from the custom home mod overhauls

I used to have ELFX in an earlier group for this reason.
But I moved it up due some people preferring to put the ELFX weather module before the main ELFX module.
The ELFX weather module may also need to be sorted after the ELFX Enhancer/Hardcore module, at least according to [ELFX Weathers - No Eye-Adaptation - Less Bloom Blur - More Contrast - FPS Fix](https://www.nexusmods.com/skyrimspecialedition/mods/43117).
So there's no way to cover all of these situations/preferences.

I don't think anyone wants to go out and test how each vanilla/DLC housing mod sorts against the NO Homes modules.
Placing vanilla/DLC housing mods in a later group would also be problematic due to the number of potential files.
There also isn't a good static position for them relative to lighting overhauls, Immersive Citizens, Open Cities etc.
And it's easier to leave them in the default group so that their position is as dynamic as possible to suit as many load orders as possible.

So moving the main ELFX module and the No Homes modules back to early loaders would be easiest for maintenance.
ELFX Weather and Exteriors can stay in the default group.

**Comment by KhrysINXS** [comment]
OK. I completely get this. How about another approach that wont have such a universal chain reaction of events. 
Instead of the focus altering ELFX at all, how's about altering the:
Eli_Breezehome.esp https://www.nexusmods.com/skyrimspecialedition/mods/48931 
to work in light for this attached photo taken from the MISC. "IN THE EVENT OF" GENERAL section of the 
Eli Opt. Pkg's & Patches Page https://imgur.com/Ps0tYZ6

Speaking of this page MacSplody; Its been a very long time (probably) since you checked it out. Lots could use LOOT updating. More simple making LOOT adjustments for this page rather then to touching the bigger mods. Keeps life easier

**Comment by MacSplody** [comment]
Closing and will review further changes as part of https://github.com/loot/skyrimse/issues/2200.
