### ISSUE TITLE
Water for ENB (+ patches) should be prior to Lux (+ patches)

### ISSUE THREAD

**Issue by iSupremacy** [loot/skyrimse#2486]
I heard I could suggest load order rules here? Sorry if wrong place

LOOT tends to put Water for ENB patches after Lux.

Examples. (from W4E FOMOD and Cities of the North Patch Collection FOMOD)
Water for ENB (Shades of Skyrim).esp
Water for ENB - Patch - Landscape Fixes for Grass Mods.esp
COTN Falkreath - Water for ENB Patch.esp
Water for ENB - Patch - Clear Interior Water.esp
Water for ENB - Patch - Volcanic Water.esp

Should be:

Lux Orbis
Water for ENB
Lux

Example (Priority order 419-480)

- Water for ENB (Shades of Skyrim).esp
- Water for ENB - Patch - Landscape Fixes for Grass Mods.esp
- COTN Falkreath - Water for ENB Patch.esp
- Water for ENB - Patch - Clear Interior Water.esp
- Water for ENB - Patch - Volcanic Water.esp
- Lux.esp
- Lux - COTN Falkreath patch.esp
- Lux - COTN Morthal patch.esp
- Lux - COTN Dawnstar patch.esp
- Lux - Divine Elegance patch.esp
- Lux - SLaWF patch.esp
- Lux - JK's Bannered Mare patch.esp
- Lux - JK's Bee and Barb patch.esp
- Lux - JK's Candlehearth Hall patch.esp
- Lux - Great Village of Shor's Stone patch.esp
- Lux - JK's Angelines Aromatics patch.esp
- Lux - JK's Arcadia's Cauldron patch.esp
- Lux - JK's Arnleif and Sons Trading Company patch.esp
- Lux - JK's Belethor's General Goods patch.esp
- Lux - JK's Bits and Pieces patch.esp
- Lux - JK's Blue Palace patch.esp
- Lux - JK's Elgrims Elixirs patch.esp
- Lux - JK's Haelga's Bunkhouse patch.esp
- Lux - JK's Mistveil Keep patch.esp
- Lux - JK's New Gnisis Cornerclub patch.esp
- Lux - JK's Palace of Kings patch.esp
- Lux - JK's Pawned Prawn patch.esp
- Lux - JK's Radiant Raiment patch.esp
- Lux - JK's Sadris Used Wares patch.esp
- Lux - JK's Temple of Dibella patch.esp
- Lux - JK's Temple of Divines patch.esp
- Lux - JK's Temple of Kynareth patch.esp
- Lux - JK's Temple of Mara patch.esp
- Lux - JK's Temple of Talos patch.esp
- Lux - JK's The Hag's Cure patch.esp
- Lux - JK's Understone Keep patch.esp
- Lux - JK's White Phial patch.esp
- Lux - JK's Winking Skeever patch.esp
- JKs Winking Skeever - SPO Lux patch.esp
- Lux - Breezehome by Lupus patch.esp
- Lux - Embers XD patch.esp
- Lux - USSEP patch.esp
- Lux - JK's Blood Inn patch.esp
- Lux - JK's Ragged Flagon patch.esp
- Lux - JK's Riverwood Trader patch.esp
- Lux - Great Village of Ivarstead patch.esp
- Lux - Great Village of Karthwasten patch.esp
- Lux - Great Village of Kynesgrove patch.esp
- Lux - Great Village of Mixwater Mill patch.esp
- Lux - Great Village of Old Hroldan patch.esp
- Lux - Pilgrims Patch.esp
- Lux - The Great City of Dragon Bridge patch.esp
- Lux - The Great City of Rorikstead patch.esp
- Embers XD - Breezehome By Lupus - Lux - Patch.esp

**Comment by sibir-ine** [comment]
They sort that way because Lux is in the **Interior Lighting** group while Water for ENB is in the **Late Loaders** group, where **Late Loaders** loads after **Interior Lighting**. Patches that are dependent on either mod will generally follow that order as a result. From the looks of it, they'll conflict whichever way you sort them, so they'll still require a patch & there isn't exactly a correct way to sort them.

However, @MacSplody has been considering moving **Late Loaders** to an earlier position in #2200, so maybe they might want to move it before **Interior Lighting** or move **Interior Lighting** later as well.

Otherwise, if you really want them to sort the other way around, you could override their groups in the metadata editor. Be advised that this could have other adverse effects (e.g., cyclic interactions, load rules that were implicitly enforced by groups may no longer be enforced).
