### ISSUE TITLE
Load order for The Great Cities of JK's North - Patch

### ISSUE THREAD

**Issue by suamor** [loot/skyrimse#2501]
See #2500 for the list of TGC / COTN / JK's Skyrim + Patches mods (and links).
In addition I have installed [COTN - Dawnstar](https://www.nexusmods.com/skyrimspecialedition/mods/28952) and [COTN - Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/40088).
After sorting load order I have compatibility problems in game (in both cities).
I found that the load order is not correct. 
Description of correct load order can be found in mod description of [The great cities of JK's North](https://www.nexusmods.com/skyrimspecialedition/mods/33687).

**Comment by MacSplody** [comment]
> After sorting load order I have compatibility problems in game (in both cities).

Can you supply your load order that LOOT is producing?

![image](https://user-images.githubusercontent.com/1944639/181444737-c7db8c02-9c59-4455-baa4-35dfc906f728.png)

**Comment by sibir-ine** [comment]
For the Great Cities of JK's North, you need CotN Falkreath & Morthal as well. There's an old, unsupported version without CotN Falkreath & Winterhold, but no version without CotN Morthal. If `The Great Cities of JK's North - Patch.esp` is actually active in your load order & no required plugins are missing, LOOT will follow the recommended load order. An exception is for CotN Falkreath as that appears to have been added as a requirement for the patch since the last time it was updated in LOOT. I'll fix that in a bit. The only other exception is if you've added master flags to any of the required plugins (e.g., for the reference handle cap) as we've added conditions to the load afters to prioritize preventing cyclic interactions.
