### ISSUE TITLE
Add entry for Relationship Dialogue Overhaul - RDO SE

### ISSUE THREAD

**Issue by Freso** [loot/skyrimse#263]
@eFrysTon mentioned this on Discord:
> https://www.nexusmods.com/skyrimspecialedition/mods/1187/?tab=description
> contains pretty extensive load order recommendations, the large majority of which is not accounted for in the metadata for it in LOOT
> also the need for a patch when used with USSEP or CRF

`.modgroup` @eFrysTon is using to keep track of RDO conflicts in his setup, which may or may not be useful:
```.modgroup
[Relationship Dialogue Overhaul - Update]
Update.esm
Relationship Dialogue Overhaul.esp

[Relationship Dialogue Overhaul - HearthFires]
HearthFires.esm
Relationship Dialogue Overhaul.esp

[Relationship Dialogue Overhaul - Dragonborn]
Dragonborn.esm
Relationship Dialogue Overhaul.esp

[Relationship Dialogue Overhaul - Unofficial Skyrim Special Edition Patch]
Unofficial Skyrim Special Edition Patch.esp
-Cutting Room Floor.esp
Relationship Dialogue Overhaul.esp
RDO - CRF + USSEP Patch.esp

[Relationship Dialogue Overhaul - Cutting Room Floor]
-Unofficial Skyrim Special Edition Patch.esp
Cutting Room Floor.esp
Relationship Dialogue Overhaul.esp
RDO - CRF + USSEP Patch.esp
```

**Comment by MacSplody** [comment]
Already included. https://github.com/loot/skyrimse/blob/v0.13/masterlist.yaml#L2857

**Comment by ElminsterAU** [comment]
The list in the modgroups is not exhaustive. In my original comment I was referring to primarily this "load after" recommendations on the the RDO page:
- Alternate Start - Live Another Life (LAL)

I can confirm that loading RDO after LAL reduces conflicts to one single minor one, which can either be ignored or fixed with a patch which can be easily fixed with a patch.

Also, I found a minor incompatibility with Convenient Horses, which can also only be patched and not resolved by load order.

I created both patches for myself, they aren't currently published anywhere except here: https://cdn.discordapp.com/attachments/474114115414261760/474784273635999764/Relationship_Dialogue_Overhaul_-_Patches.7z

**Comment by MacSplody** [comment]
@eFrysTon It will load after Alternate Start - Live Another Life (LAL) now because of its group.
https://github.com/loot/skyrimse/commit/00bf2e1#diff-34506ac92324a5cb27264d55e4cb3258R2806

default -> Alt start group -> iCitizens (Immersive citizens & RDO)

Convenient horses is set to load after ICAIO & RDO because of that conflict. Its more of an issue for CH if it loses, but I agree a patch is really needed. I'm not sure what the policy is on patches that aren't published is tbh, will have to check that, I know I saw it somewhere.

edit: Right found it here https://loot.github.io/docs/team/Team-Policies.html

> Plugin Addition
>It's pretty simple: if a plugin is, or will shortly be (eg. author giving heads-up about imminent release), publicly available for download, it is eligible for addition to the appropriate masterlist.

>Plugins that are not available to the public are not suitable for inclusion in the masterlist
