### ISSUE TITLE
Need help with Load Order and mod crashing

### ISSUE THREAD

**Issue by sashpot** [loot/skyrimse#281]
Hey,
I'm sort of new to modding (heavy modding in any case), and I've run into a problem that I'm unsure how to fix. At first I thought it was just an issue with NPC bodies littering the game causing stuttering and crash, but now I think it may be a texture from CBBE as when starting a new character in RaceMenu I switch to female sex and the game freezes and CTD without any other given warnings. The game was running very well up until I installed RaceMenu and XP32, however, after uninstalling said mods from all profiles the crashing persisted. In fact I think it's become more pronounced as there is no delay -to the crash- as I was able to walk around for a number of seconds previously.

Additionally, and I'm not sure if anyone can even help me here, but I've struggled to get an ENB working as the d3da11.dll is also causing hard crashes, is there a simple fix to this?

Again, I'm quite new to heavy modding so please forgive me if this is a commonly placed issue.

[CEFDebugLog.txt](https://github.com/loot/skyrimse/files/2279871/CEFDebugLog.txt)

[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/2279872/LOOTDebugLog.txt)

And
[LoadOrder_SkyrimSE_2018-08-11T13-09-40.txt](https://github.com/loot/skyrimse/files/2279869/LoadOrder_SkyrimSE_2018-08-11T13-09-40.txt)

Please let me know if there's more information you need.

Thanks,
Sasha

**Comment by pStyl3** [comment]
Seeing as you posted a CEFDebugLog.txt, it means that you don't use the latest version of LOOT, so we strongly recommend you install LOOT 0.13.1. Furthermore, your LOOTDebugLog.txt is basically empty, you need to enable Debug Logging within LOOT's settings so that important information get's actually logged.

That being said, this doesn't seem to be a LOOT issue, as such I'm closing this issue. If you need general modding guidance, you're best bet would be to ask for help either on the Nexus forums or some equivalant site regarding modding Skyrim.
