### ISSUE TITLE
Curse of the Dragonborn REDUX special load order instructions

### ISSUE THREAD

**Issue by SkyLover264** [loot/skyrimse#2873]
https://www.nexusmods.com/skyrimspecialedition/mods/104477?tab=description

Putting this here because I have no idea how to implement something like this, or if there's even an easy way to do it. LOOT places this mod near the bottom of the load order, but the description page says that the mod should be loaded before any vampire and/or werewolf overhauls are loaded. It's also been noted in the comments that this mod will require minor conflict resolution with any mods that modify the ring of hircine, though I'm not 100% sure that's the sort of thing LOOT would push a notification for.

**Comment by sibir-ine** [comment]
It can be added to the **Early Loaders** group. Since it's sorted before the default group, the plugin will be sorted before most mods, including any vampire & werewolf overhauls. As for conflicts, if you know which specific mods that it conflicts with, individual messages can be added indicating that a patch is recommended & is either available (& from where) or not known to be available.

**Comment by SkyLover264** [comment]
Thanks for the tip. I genuinely didn't know Early Loaders was a thing. I've submitted a poll request to do that.

**Comment by pStyl3** [comment]
@SkyLover264 I've requested one more change for your PR, please take a look.
