### ISSUE TITLE
touring carriages MUST be loaded below immersive citizens or crashes will occur 

### ISSUE THREAD

**Issue by maxcorrice** [loot/skyrimse#331]
cutting room floor doesn't like this, but ive never had an issue between them when loaded with touring carriages lower down

**Comment by MacSplody** [comment]
@maxcorrice It's never been an issue before, and that rule has been in the masterlist since LE version.

Please provide some proof:
1. Your load order at the time of the crash.
    - This will help in ruling out any other mods as being the cause of the crash.
2. Minimum Steps to replicate the crash.

Can you replicate the crash on a test save with only:
- `TouringCarriages.esp`
- `Immersive Citizens - AI Overhaul.esp`
- `Immersive Citizens - TC patch.esp`

> cutting room floor doesn't like this, but ive never had an issue between them when loaded with touring carriages lower down

Cutting Room floor must be loaded after Touring Carriages due to `NAVM` edits.
It was also requested by the author of Cutting Room floor.
