### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Winger34** [loot/skyrimse#42]
Loot is not working I try to use it but it keeps on giving me an error LOOTDebugLog.txt message how can I fix it 
PS: I'm playing Skyrim SE

**Comment by Ortham** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.

Also the issue seems like a potential application issue rather than a metadata issue, so should be filed in the loot/loot repository's issue tracker.
