### ISSUE TITLE
Issue of SKSE detection when skse64_loader.exe has been renamed to Skyrim.exe

### ISSUE THREAD

**Issue by SojournerOne** [loot/skyrimse#548]
I would like to suggest fix for people who have renamed skse64_loader.exe in order to launch the SKSE through the Steam launcher, so that LOOT won't give error messages: look for SKSE.ini with contents:

[Loader]
RuntimeName=Skyrim.exe

inside Steam\steamapps\common\Skyrim Special Edition\Data\skse

**Comment by MacSplody** [comment]
No because it can't be done through the masterlist.
The warning messages can be disabled from inside LOOT if it really bothers people.

![image](https://user-images.githubusercontent.com/1944639/50387469-eb3de600-06f4-11e9-99af-48bf250e760d.png)
![image](https://user-images.githubusercontent.com/1944639/50387479-2b9d6400-06f5-11e9-9f95-52edadaaab82.png)

**Comment by SojournerOne** [comment]
I did not know about that feature, thanks for the heads up!

Another fix is to put an unmodified duplicate of skse64_loader.exe into the root folder. So obvious I should have realized before bothering anybody...*sheepish grin*
