### ISSUE TITLE
RDO can load after Alternate Start

### ISSUE THREAD

**Issue by CalebSica** [loot/skyrimse#576]
According to the [RDO mod page](https://www.nexusmods.com/skyrimspecialedition/mods/1187), [Alternate Start - Live Another Life.esp](https://www.nexusmods.com/skyrimspecialedition/mods/272) should load before Relationship Dialogue Overhaul.esp

Edit: Also looking at xEdit conflicts and according to the author [here](https://forums.nexusmods.com/index.php?/topic/2792539-immersive-citizens-ai-overhaul/?p=26876829), Alternate Start should load before Immersive Citizens - AI Overhaul.esp

**Comment by MacSplody** [comment]
HI @Ca1ebS

> Alternate Start - Live Another Life (LAL)
>     A handful of records conflict between RDO and LAL. RDO includes the changes made to these conflicting records by LAL, and therefore should be loaded after LAL so that changes from both mods are applied.

This may have been true at one point, but ASLAL is still receiving updates, while RDO is not.

This is a change RDO is not forwarding.
![image](https://user-images.githubusercontent.com/1944639/50631404-09e57d80-0f3c-11e9-807b-3a20e0045471.png)

Also taken from the RDO page.

>6. Load Order:
Load order is very important with RDO to make sure the correct mod(s) is winning the record conflicts.
Compatibility patches have been provided for several mods, but not for every mod that RDO will conflict with.
If you are unsure of where to place RDO in your load order and are afraid that it will mess up the mods you have installed, place RDO further up in your load order. This will allow your existing mods to continue to work but may cause a feature from RDO to not be seen in-game or a dialogue correction made by RDO may not be carried over. **This will NOT break RDO**.

The main reason I have not added those two rules
```
ICAIO after ASLAL
and 
RDO after ICAIO
```
Is because it's not optimal for every load order.

User can still manually set those mods to load after ASLAL if they wish to do so.
![image](https://user-images.githubusercontent.com/1944639/50633334-d823e500-0f42-11e9-8dd9-d640e65553d6.png)

**Comment by CalebSica** [comment]
Okay, I understand why you wouldn't place RDO after LAL, but looking at xEdit for ICAIO and LAL, it does seem like LAL should always load before ICAIO. This is the only conflict these two mods have: 
![screenshot_1](https://user-images.githubusercontent.com/6210484/50658877-b5a4c280-0f68-11e9-832b-7beaaeb7e08e.png)

**Comment by MacSplody** [comment]
@Ca1ebS Testing at the moment for RDO & ICAIO after ASLAL. @Arthmoor said the above conflict with RDO is not important. https://discordapp.com/channels/473542112974077963/473543945188802580/530464689780686853

There are other mods which need to load after RDO & ICAIO, so I need to make sure those don't cause any issues if loaded after ASLAL.

**Comment by Arthmoor** [comment]
In the particular case you list for ICAO and LAL, ICAO is cancelling out fixes that LAL forwards in from USSEP. Specifically that bunch of stuff down there in the actions for head tracking. Notice that ICAO blocks those. ICAO does a lot of stuff like this that's detrimental to bug fixes being forwarded in other mods and should not be loading after them because it's reintroducing broken behavior even if it carried LAL's edits for the phase conditions.
