### ISSUE TITLE
Load order for Atlas Map Markers and Complete Alchemy & Cooking Overhaul.

### ISSUE THREAD

**Issue by kryptopyr** [loot/skyrimse#701]
"Atlas Map Markers.esp" needs to load after "Complete Alchemy & Cooking Overhaul.esp" due to a conflict over worldspace records.  No patch is needed as long as Atlas is allowed to overwrite CACO.
I'm pretty sure this would apply to the original Atlas Map Markers as well as my "MCM" version.

**Comment by MacSplody** [comment]
@kryptopyr Okay, I'll update that, thanks for the info.

**Comment by MacSplody** [comment]
MLU also overwrites one change.
![image](https://user-images.githubusercontent.com/1944639/59575712-8b793400-90b4-11e9-8462-82fa87b8f401.png)

Two Conflicts with ELE_SSE, that might need a patch since it sorts after Open Cities without conflict.

![image](https://user-images.githubusercontent.com/1944639/59577382-77850080-90bb-11e9-8255-27b06a7047c1.png)

Atlas Map Markers does conflict with Open Cities, so that version can't sort after ELE.
![image](https://user-images.githubusercontent.com/1944639/59579479-eadf4000-90c4-11e9-8789-e3bb43848d1e.png)

Other Conflicts are [Paper World Map](https://www.nexusmods.com/skyrimspecialedition/mods/10836) & [A Quality World Map Paper](https://www.nexusmods.com/skyrimspecialedition/mods/5804). And [Paper World Map Flat Mesh with Unofficial Fix and Flat Map Markers](https://www.nexusmods.com/skyrimspecialedition/mods/23114)
![image](https://user-images.githubusercontent.com/1944639/59580776-5f68ad80-90ca-11e9-9e6d-eb11c53617f1.png)

**Comment by MacSplody** [comment]
https://discordapp.com/channels/473542112974077963/496196499890241546/592050039262543912

![image](https://user-images.githubusercontent.com/1944639/59967276-be418300-951f-11e9-919a-788b682d02cf.png)

**Comment by kryptopyr** [comment]
Another conflict:  [Amulets of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/487).  Loading Atlas Map Markers.esp after SL01AmuletsSkyrim.esp is will resolve this conflict.
