### ISSUE TITLE
OBIS and SkyTest should be sorted after Skyrim Revamped, OBIS also after Diverse Skyrim.

### ISSUE THREAD

**Issue by Soukmancer** [loot/skyrimse#705]
Skyrim Revamped makes changes to race : animal stats... as well as npc: bandit types ... this puts them into conflict...  Skyrim Revamped is fairly far reaching and makes changes to many npc and race values... it will override Organized bandits in skyrim and Skytest where those mods are dedicated to improving bandits and animals.  Loading OBIS and SkyTest after will preserve those mods changes to bandits and animals while preserving the rest of Revamps changes to monsters and bosses.

The author of Skyrim Revamped also recommends this load order ... 

Diverse Skyrim also changes 1 bandit type entry, again it make more sense to have OBIS changes preserved over Diverse Skyrim.  

SRCEO https://www.nexusmods.com/skyrimspecialedition/mods/14598
OBIS https://www.nexusmods.com/skyrimspecialedition/mods/26766/
SkyTest: https://www.nexusmods.com/skyrimspecialedition/mods/1104
Diverse Skyrim: https://www.nexusmods.com/skyrimspecialedition/mods/7707

**Comment by MacSplody** [comment]
Default sorting is placing OBIS after SRCEO.

![image](https://user-images.githubusercontent.com/1944639/59819293-1f4e3880-931f-11e9-85f5-d60d2a9c49dc.png)

Must be one of SRCEO's afters that is affecting it.

```yaml
    after:
      - 'Cloaks.esp'
      - 'Combat Evolved.esp'
      - 'Immersive Weapons.esp'
      - 'Skyrim Immersive Creatures Special Edition.esp'
      - 'WICO - Immersive People.esp'
      - 'Wildcat - Combat of Skyrim.esp'
```

Seems to be Cloaks, as it conflicts with both OBIS & SRCEO.
Since default sorting places Cloaks after both, but the SRCEO after for Cloaks places it below OBIS.

This also includes patches for Cloaks in [QUASIPC](https://www.nexusmods.com/skyrimspecialedition/mods/18369)

**Comment by MacSplody** [comment]
> Diverse Skyrim also changes 1 bandit type entry, again it make more sense to have OBIS changes preserved over Diverse Skyrim.

It's pretty minor, but yes it makes more sense for OBIS to be after Diverse Skyrim, since OBIS is overhauling Bandits.

Also a bashed patched will only produce the correct result with OBIS after Diverse,
as they both have `Delev` and `Relev` tags.

![image](https://user-images.githubusercontent.com/1944639/59825531-2b8cc280-932c-11e9-83b3-fa7a60ca6253.png)

**Comment by Soukmancer** [comment]
Hm, I was using the MO2 sort button if that makes any difference.  I'll test again and make sure I sort via LOOT proper.  Oh and I do use cloaks of skyrim so I guess that's the reason?  It's moving the plugins due to conflict?

Also the author of wildcat and the author of SRCEO recommend SRCEO load after wildcat... though it likely comes down to a preference thing for combat styles.  I don't believe the two plugins conflict.

**Comment by MacSplody** [comment]
> odd I was using the MO2 sort button and for some reason it put revamped after OBIS. I'll test again and make sure I sort via LOOT proper

It might not be updating the masterlist if you use MO2 sort, I think that was changed recently.

>  Oh and I do use cloaks of skyrim so I guess that's the reason? It's moving the plugins due to conflict?

Yes, Cloaks should now be before both OBIS & SRCEO because of its group.
