### ISSUE TITLE
Can Soulmancer Music merge be sorted lower?

### ISSUE THREAD

**Issue by Soukmancer** [loot/skyrimse#706]
My plugin seems to run into conflicts with a few mods even where they don't modify the same cell in any way.  For some reason the named mods that load after reference these cells in conflict, even though they contain entries identical to vanilla and/or USSEP with no modifications and in fact do not conflict at all.

Cloaks of skyrim, artifacts of skyrim, amulets of skyrim, ars metallica, new armory, and alternate start... in 7 cells, no edited sub records...

These mods loading after Soulmancer Music Merge Plugin will cause the new music types added to these cells to revert to vanilla, yet not benefiting the named mods in anyway as there are no visible changes to these cells to begin with.  

It would be great if the music plugin could load after these to avoid a false conflict requiring a seemingly pointless patch and false.

**Comment by MacSplody** [comment]
Okay I've tested it a bit and the main conflicts it going to have are maps, map markers, lighting, some location mods and other music mods of course.

`Paper World Map.esp`
`IcePenguinWorldMapPaper.esp`
`Atlas Legendary OCS.esp`
`Atlas Legendary.esp`
`Winterhold Restored.esp`
`OCW_Obscure's_CollegeofWinterhold.esp`
`NoGrassINCities.esp`



LeanWolfs Aemers Refuge SE.esp
2 Cell & 1 WRLD Settings Reverted
https://user-images.githubusercontent.com/1944639/59950750-bf66a780-946e-11e9-8ff4-e00c15031ff6.png

Finding_VelehkSain_MAQF.esp
1 Cell setting reverted
https://user-images.githubusercontent.com/1944639/59951017-8da21080-946f-11e9-8509-45a567e4d1b3.png

`OCW_Obscure's_CollegeofWinterhold.esp` after `Soulmancer Soundtrack - NoVindDun.esp`
5 Cell settings conflicts
7 WRLD settings reverted
https://user-images.githubusercontent.com/1944639/59951244-305a8f00-9470-11e9-836c-5adbc1dbd945.png
`Soulmancer Soundtrack - NoVindDun.esp` after `OCW_Obscure's_CollegeofWinterhold.esp`
5 Cell settings conflicts
https://user-images.githubusercontent.com/1944639/59951453-e0c89300-9470-11e9-8ddc-0764981d7fca.png
Patch required.

Ars Metallica.esp
1 Cell setting reverted
https://user-images.githubusercontent.com/1944639/59952224-52094580-9473-11e9-9598-6f2806560a94.png

NotSoFast-MageGuild.esp
1 Cell setting reverted
https://user-images.githubusercontent.com/1944639/59952507-5e41d280-9474-11e9-9280-5ab73fe52a65.png

MCWT_ACollegeCoup.esp
3 Cell setting reverted
https://user-images.githubusercontent.com/1944639/59953065-66027680-9476-11e9-8fb9-926b9c3e1688.png

MagiCollege.esp
5 Cell settings conflicts
Sort `MagiCollege.esp` after `Soulmancer Soundtrack - NoVindDun.esp`, since it cover a smaller area.
https://user-images.githubusercontent.com/1944639/59953334-6c452280-9477-11e9-97ea-e36befc3aae8.png

MCWT_ArnielsAppeals.esp
1 Cell setting reverted
https://user-images.githubusercontent.com/1944639/59953575-a662f400-9478-11e9-9ce6-9b5d08e45624.png

MCWT_GovernableGatekeeper.esp
1 Cell setting reverted
https://user-images.githubusercontent.com/1944639/59953605-d14d4800-9478-11e9-9585-183fa464ad7b.png

MCWT_ExpiditeTheExpirate.esp
1 Cell setting reverted
https://user-images.githubusercontent.com/1944639/59953664-11142f80-9479-11e9-9004-3b28cdc255e7.png

Complete Alchemy & Cooking Overhaul.esp
7 Cell settings reverted
1 WRLD setting reverted
https://user-images.githubusercontent.com/1944639/59953834-ccd55f00-9479-11e9-9f61-94d4492e696f.png

MLU.esp
31 Cell settings reverted
1 WRLD setting reverted
https://user-images.githubusercontent.com/1944639/59953990-803e5380-947a-11e9-8577-b124d7ed55b4.png

Alternate Start - Live Another Life.esp
2 Cell settings reverted
https://user-images.githubusercontent.com/1944639/59954195-62bdb980-947b-11e9-9ef4-1d7277434e39.png

Requiem.esp
53 Cell settings reverted
1 WRLD setting reverted
https://user-images.githubusercontent.com/1944639/59956493-99e69780-9488-11e9-9067-0583e99bed86.png

Immersive Citizens - AI Overhaul.esp
1 Cell setting  conflict
https://user-images.githubusercontent.com/1944639/59956700-c0590280-9489-11e9-906e-6e725a17e22e.png
8 Cell settings reverted
https://user-images.githubusercontent.com/1944639/59956659-6ce6b480-9489-11e9-827d-41d80717d593.png

Winterhold Restored.esp
2 Cell setting  conflicts, patch recommended.
https://user-images.githubusercontent.com/1944639/59956851-f054d580-948a-11e9-9ccf-94f0437e1f9d.png
4 Cell settings reverted
https://user-images.githubusercontent.com/1944639/59956830-d1eeda00-948a-11e9-8946-7ea0311151ab.png

Open Cities Skyrim.esp
11 Cell settings reverted
https://user-images.githubusercontent.com/1944639/59957684-92c48700-9492-11e9-9d02-8adf596d1611.png
https://user-images.githubusercontent.com/1944639/59957648-49743780-9492-11e9-8a60-5bc67e42157b.png

Immersive Citizens - OCS patch.esp
2 Cell settings reverted
https://user-images.githubusercontent.com/1944639/59957709-e040f400-9492-11e9-8217-f59e2567f2ea.png

No Conflicts

TheChoiceIsYours.esp
Provincial Courier Service.esp
MissingEZsFixed.esp
MissingEZs_AllExteriors.esp

**Comment by Soukmancer** [comment]
Ok thanks, can it then be sorted after the ones where its not causing a
conflicting change? Stuff like AS and Ars Metallica doesn't make any changes
in the conflicting cells and is just a copy/paste of vanilla / ussep, which are
carried forward in my mod aside from the mustype, so all conflicts with
those 2 specifically will be resolved simply if mine loads after them.  I guess the main thing I gotta figure out is, what can the music mod be sorted after to resolve the conflict and what needs
manual patching.  Although I see you have included notes for specific mods that do need a patch, does that mean the others can be resolved just by sorting mine with higher priority / lower load order?

Thanks

**Comment by MacSplody** [comment]
@Soukmancer Afters for those mods have been added. Thanks.

**Comment by MacSplody** [comment]
A couple more mods.

`Bring Out Your Dead.esp`
`Skyshards.esp`
`SkyrimReputation_SSE.esp`

![image](https://user-images.githubusercontent.com/1944639/59996103-44a9b200-9651-11e9-8f44-c05eecc42838.png)

![image](https://user-images.githubusercontent.com/1944639/59997045-c8649e00-9653-11e9-9e89-45c61a63d75a.png)
