### ISSUE TITLE
3DNPC and MoonAndStar ESP Sort Failure

### ISSUE THREAD

**Issue by easelgames** [loot/skyrimse#830]
LOOT does not allow for sorting with 3DNPCs and Moon and Star MAS.esp in the load order... Using versions from Nexus, latest version of loot, and both mods as of time of posting. (oct3-19) EDIT: Default Loot Settings, no custom sort orders used

![LOOT_9MXBeyLkoC](https://user-images.githubusercontent.com/46850157/66137812-a3c18000-e5cb-11e9-8111-dbb2dacefd44.png)

**Comment by MacSplody** [comment]
[Interesting NPCs SE](https://www.nexusmods.com/skyrimspecialedition/mods/29194)

![image](https://user-images.githubusercontent.com/1944639/66139111-c36e9d80-e5f7-11e9-9b9b-88bca8b0360d.png)

Yeah ESM flagging can potentially cause issues with existing rules.

I'll have a look at it soon and see if there's a good way to resolve it.

**Comment by easelgames** [comment]
I didn't think about the ESM version. I've been grabbing so many mods lately just trying to get ideas. So I hadn't remembered. Thanks

**Comment by easelgames** [comment]
I see you mentioned a few NAVM conflicts with 3DNPCs and M&Star. Any chance you could mention those to 3DNPC for a patch in the future maybe? (on nexus) I mention them because M&S is an older mod that may not be being worked on anymore I'm not sure.

**Comment by MacSplody** [comment]
Anyone can make a patch request.
So you may as well ask them if you want one, they can only say no.

It's two NAVM so it doesn't look too bad, but it would need to be checked in game or the Creation Kit for any other conflicts. The reason 3DNPCs was after is because it had a new door connection and MaS does not in those two NAVM.

![image](https://user-images.githubusercontent.com/1944639/66154237-ebb8c500-e614-11e9-9d77-715e75a0e1e1.png)
